### ISSUE TITLE
Using a prefix for the secrets bucket doesn't work

### ISSUE THREAD

**Issue by mikekap** [buildkite/buildkite-aws-elastic-stack#45]
It ends up missing the bucket-level permission to list objects. That is, given a prefix like `foo/bar`, we need IAM permissions for: `arn:aws:s3:::foo/bar/*` & `arn:aws:s3:::foo`, but the IAM config misses the second one.

**Comment by lox** [comment]
Why do you need list permissions?

**Comment by mikekap** [comment]
I believe it's because `s3_exists` uses it @ https://github.com/buildkite/buildkite-aws-stack/blob/master/packer/conf/hooks/environment#L5

**Comment by lox** [comment]
Interesting. I wonder why we haven't run into this issue before. I will dig a bit more.

**Comment by lox** [comment]
Hi @mikekap, are you still having this issue? Do you have any more details like a specific error message?

**Comment by mikekap** [comment]
I could try again, but unless the IAM policy changed, I think the issue is still there. The error I was seeing was something like "403 during ListBucket operation".

http://blogs.aws.amazon.com/security/post/Tx1P2T3LFXXCNB5/Writing-IAM-policies-Grant-access-to-user-specific-folders-in-an-Amazon-S3-bucke has a good example of how to whitelist a prefix with IAM. The `resource` should be the bucket name (not `bucket/prefix`), and the `Condition` should have a "must have prefix" clause.

**Comment by toolmantim** [comment]
I haven't seen this crop up again with lots of testing… so I'm going to mark it as closed! But if it does happen please just re-open and we can investigate.
