### ISSUE TITLE
Ability to customize gc-docker rules

### ISSUE THREAD

**Issue by toolmantim** [buildkite/buildkite-aws-elastic-stack#78]
At the moment the hourly cleaning of Docker images is a bummer for caches… especially on our builder machine. I'd be neat to support a S3 file containing the gc-docker rules… or perhaps just paste them in as a stack parameter?

**Comment by lox** [comment]
I'd suggest we ditch docker-gc entirely, or at least only run it if disk space is an issue.

**Comment by toolmantim** [comment]
I'm fine with that! I'll just axe it.

**Comment by toolmantim** [comment]
I think we should probably keep it for long-lived persistent machines, because Docker will fill things up pretty quick, but increase the TTL of images to 3 days, or 1 week, or something more than 30 minutes. And also enable the `FORCE_IMAGE_REMOVAL` option (https://github.com/spotify/docker-gc#forcing-deletion-of-images-that-have-multiple-tags) whilst we're there.
